### ISSUE TITLE
0xca05d6db7dbf83dd9c631f05c7c600957025a5bb

### ISSUE THREAD

**Issue by perfectq** [swaldman/eth-quip-client#2]

**Comment by swaldman** [comment]
OMG! I feel kind of awful. I didn't see this address, as it was posted as a separate issue rather than as a comment to the prior issue. Let me know if you are still interested in playing and I will send you a bit of Ether.

I am so sorry.

**Comment by swaldman** [comment]
Also, if you are still interested in playing, please update to the latest version that fixes the glitches you guys helped me discover. See https://github.com/swaldman/eth-quip-client/issues/1#issuecomment-541561283
